# GitHub Pages Configuration - serve site assets
# Keep minimal settings; .nojekyll will bypass Jekyll

title: "Agent Exo-Suit V5.0"
description: "Revolutionary AI Development Platform"
url: "https://bigrob7605.github.io"
baseurl: "/Exo-Suit"

plugins: []
collections: {}
defaults: []
markdown: kramdown
encoding: utf-8
