# Jekyll Configuration for Agent Exo-Suit V5.0
# Clean, minimal configuration to fix GitHub Pages build issues

# Site settings
title: "Agent Exo-Suit V5.0 - Revolutionary AI Development Platform"
description: "Revolutionary AI-powered development tools featuring 43 operational components with enterprise-grade performance, security, and automation"
url: "https://bigrob7605.github.io"
baseurl: "/Exo-Suit"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: utf-8

# Exclude problematic files and directories
exclude:
  # System and build files
  - ".git/"
  - ".venv/"
  - "node_modules/"
  - "vendor/"
  
  # Large data and log files
  - "*.log"
  - "*.tgz"
  - "*.zip"
  - "*.tar"
  - "logs/"
  - "cache/"
  - "temp/"
  
  # Source code and scripts (not needed for docs)
  - "*.ps1"
  - "*.py"
  - "*.bat"
  - "*.sh"
  - "*.js"
  - "*.ts"
  - "*.json"
  - "*.xml"
  - "*.yml"
  - "*.yaml"
  
  # Directories with source code
  - "ops/"
  - "rag/"
  - "context/"
  - "mermaid/"
  - "cursor/"
  - "config/"
  - "generated_code/"
  - "system_backups/"
  - "archive/"
  - "legacy/"
  
  # Requirements and config files
  - "requirements*.txt"
  - "package*.json"
  - "*.lock"
  - ".env*"
  
  # Test and temporary files
  - "test*/"
  - "temp*/"
  - "backup*/"
  - "*.test"
  - "*.spec"

# Include only essential documentation
include:
  - "README.md"
  - "*.md"

# Collections (simplified)
collections:
  docs:
    output: true
    permalink: /docs/:name/

# Plugins (minimal for GitHub Pages compatibility)
plugins: []

# Defaults (simplified)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Build optimization
incremental: false
relative_links: false
future: false
