# GitHub Pages Configuration for Agent Exo-Suit V5.0
# Optimized to prevent deployment loops and ensure stable hosting

# Site settings
title: "Agent Exo-Suit V5.0 - Revolutionary AI Development Platform"
description: "Revolutionary AI-powered development tools featuring 43 operational components with enterprise-grade performance, security, and automation"
url: "https://bigrob7605.github.io"
baseurl: "/Exo-Suit"

# Disable Jekyll processing to prevent build loops
plugins: []
collections: {}
defaults: []

# Build settings
markdown: kramdown
encoding: utf-8
