# Minimal Jekyll Configuration for Agent Exo-Suit V5.0
# This configuration prevents all Jekyll processing to break deploy loops

# Site settings
title: "Agent Exo-Suit V5.0 - Revolutionary AI Development Platform"
description: "Revolutionary AI-powered development tools featuring 43 operational components with enterprise-grade performance, security, and automation"
url: "https://bigrob7605.github.io"
baseurl: "/Exo-Suit"

# Completely disable Jekyll processing
exclude: ["*"]
include: []
plugins: []
collections: {}
defaults: []

# Minimal build settings
markdown: kramdown
encoding: utf-8
