# GitHub Pages Configuration for Agent Exo-Suit V5.0
# Minimal static site configuration - no Jekyll processing

# Site settings
title: "Agent Exo-Suit V5.0 - Revolutionary AI Development Platform"
description: "Revolutionary AI-powered development tools featuring 43 operational components with enterprise-grade performance, security, and automation"
url: "https://bigrob7605.github.io"
baseurl: "/Exo-Suit"

# Force static site mode - no Jekyll
plugins: []
collections: {}
defaults: []
exclude: ["*"]
include: ["index.html"]
markdown: kramdown
encoding: utf-8
