# Minimal Jekyll Configuration for Agent Exo-Suit V5.0
# This configuration prevents Jekyll processing and serves files directly

# Site settings
title: "Agent Exo-Suit V5.0 - Revolutionary AI Development Platform"
description: "Revolutionary AI-powered development tools featuring 43 operational components with enterprise-grade performance, security, and automation"
url: "https://bigrob7605.github.io"
baseurl: "/Exo-Suit"

# Disable Jekyll processing
exclude: ["*"]
include: []

# No plugins, no collections, no processing
plugins: []
collections: {}
defaults: []

# Build settings (minimal)
markdown: kramdown
highlighter: rouge
encoding: utf-8
