# Agent Exo-Suit V4.0 - Dual-Mode RAG Configuration
# Optimized for Windows with GPU acceleration and CPU fallback

# Device Configuration
device:
  primary: "auto"  # auto, cuda, cpu
  fallback: "cpu"  # fallback device if primary fails
  hybrid_mode: true  # enable CPU+GPU hybrid processing
  
# Model Configuration
model:
  name: "all-MiniLM-L6-v2"  # lightweight, fast model
  max_length: 512  # maximum sequence length
  batch_size: 32  # batch size for processing
  
# Processing Configuration
processing:
  chunk_size: 512  # text chunk size
  chunk_overlap: 50  # overlap between chunks
  max_file_size: 10485760  # 10MB max file size
  supported_extensions: [".txt", ".md", ".py", ".js", ".html", ".css", ".json", ".xml", ".yaml", ".yml"]
  
# Index Configuration
index:
  type: "flat"  # FAISS index type
  normalize: true  # normalize vectors for cosine similarity
  save_format: "faiss"  # index save format
  
# Performance Configuration
performance:
  use_gpu_memory_pool: true  # optimize GPU memory usage
  cpu_threads: "auto"  # auto-detect CPU threads
  gpu_memory_fraction: 0.8  # GPU memory usage limit
  
# Windows Compatibility
windows:
  force_cpu_faiss: true  # force CPU FAISS on Windows
  encoding: "utf-8"  # default file encoding
  path_separator: "\\"  # Windows path separator
  
# Logging Configuration
logging:
  level: "INFO"
  format: "[%(levelname)s] %(message)s"
  file: "rag_v4.log"
  
# Output Configuration
output:
  base_dir: "rag"
  index_name: "index_v4"
  metadata_name: "metadata_v4"
  report_name: "build_report_v4.json"
